import { NextRequest, NextResponse } from 'next/server'
import dns from 'dns/promises'
import https from 'https'
import http from 'http'
import tls from 'tls'
export const maxDuration = 30
function sanitize(raw: string): string { return raw.replace(/^https?:\/\//i, '').replace(/^wss?:\/\//i, '').split('/')[0].split(':')[0].trim().toLowerCase() }
function validHost(h: string): boolean { return /^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*$/.test(h) || /^(\d{1,3}\.){3}\d{1,3}$/.test(h) }
async function httpFetch(url: string, timeoutMs = 8000) { return new Promise<{ status: number; headers: Record<string, string> }>((resolve, reject) => { const lib = url.startsWith('https') ? https : http; lib.get(url, { timeout: timeoutMs }, res => { const h: Record<string, string> = {}; for (const [k, v] of Object.entries(res.headers)) h[k] = typeof v === 'string' ? v : Array.isArray(v) ? v.join(', ') : String(v ?? ''); resolve({ status: res.statusCode ?? 0, headers: h }); res.resume() }).on('error', reject).on('timeout', () => reject(new Error('Timeout'))) }) }
async function checkWS(hostname: string, path: string, timeoutMs = 5000) { return new Promise<{ status: string; upgraded: boolean }>(resolve => { const req = https.request({ hostname, port: 443, path, method: 'GET', headers: { Upgrade: 'websocket', Connection: 'Upgrade', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Key': 'dGhlIHNhbXBsZSBub25jZQ==' }, timeout: timeoutMs, rejectUnauthorized: false }, res => { const u = res.statusCode === 101 && (res.headers.upgrade || '').toLowerCase() === 'websocket'; resolve({ status: String(res.statusCode ?? 0), upgraded: u }); res.resume() }); req.on('error', e => resolve({ status: 'Error', upgraded: false })); req.on('timeout', () => { req.destroy(); resolve({ status: 'Timeout', upgraded: false }) }); req.end() }) }
async function sslCheck(host: string): Promise<Record<string, string>> { return new Promise((resolve, reject) => { const sock = tls.connect({ host, port: 443, servername: host, rejectUnauthorized: false, timeout: 8000 }, () => { const cert = sock.getPeerCertificate(true); sock.destroy(); if (!cert?.subject) { resolve({ Error: 'No certificate' }); return }; const now = Date.now(); const to = cert.valid_to ? new Date(cert.valid_to).getTime() : 0; const days = Math.ceil((to - now) / 86400000); resolve({ Trusted: sock.authorized ? 'Yes' : 'No', Subject: cert.subject?.CN ?? '', Issuer: cert.issuer?.CN ?? cert.issuer?.O ?? '', Serial: cert.serialNumber ?? '', 'Valid From': cert.valid_from ?? '', Expires: cert.valid_to ?? '', 'Days Left': days > 0 ? String(days) : 'Expired', TLS: sock.getProtocol() ?? 'unknown', SANs: (cert.subjectaltname ?? '').replace(/DNS:/g, '').trim() }) }); sock.on('error', reject).on('timeout', () => { sock.destroy(); reject(new Error('TLS timeout')) }) }) }

export async function POST(req: NextRequest) {
  const { tool, host: rawHost } = (await req.json().catch(() => ({}))) as { tool: string; host: string }
  const host = sanitize(rawHost ?? ''); if (!host || !validHost(host)) return NextResponse.json({ error: 'Invalid host' }, { status: 400 })
  try {
    switch (tool) {
      case 'dns': { const [a, aaaa, mx, ns, txt, cname] = await Promise.allSettled([dns.resolve4(host), dns.resolve6(host), dns.resolveMx(host), dns.resolveNs(host), dns.resolveTxt(host), dns.resolveCname(host)]); const f: Record<string, string> = { Domain: host }; if (a.status === 'fulfilled') f['A Records'] = a.value.join(', '); if (aaaa.status === 'fulfilled') f['AAAA'] = aaaa.value.join(', '); if (mx.status === 'fulfilled') f['MX'] = mx.value.map(r => `${r.exchange}(${r.priority})`).join(', '); if (ns.status === 'fulfilled') f['NS'] = ns.value.join(', '); if (txt.status === 'fulfilled') f['TXT'] = txt.value.map(r => r.join('')).join(' | ').slice(0, 500); if (cname.status === 'fulfilled') f['CNAME'] = cname.value.join(', '); return NextResponse.json({ success: true, type: 'DNS Lookup', fields: f }) }
      case 'whois': { const f: Record<string, string> = { Domain: host }; try { const r = await fetch(`https://rdap.verisign.com/com/v1/domain/${host}`, { signal: AbortSignal.timeout(8000) }); if (r.ok) { const d = await r.json() as any; f['Registrar'] = d?.entities?.[0]?.vcardArray?.[1]?.find((v: any) => v[0] === 'fn')?.[3] ?? 'N/A'; f['Status'] = Array.isArray(d?.status) ? d.status.join(', ') : 'N/A'; if (Array.isArray(d?.events)) { for (const e of d.events) { if (e.eventAction === 'registration') f['Registered'] = e.eventDate ?? ''; if (e.eventAction === 'expiration') f['Expires'] = e.eventDate ?? ''; if (e.eventAction === 'last changed') f['Updated'] = e.eventDate ?? '' } } } } catch {}; return NextResponse.json({ success: true, type: 'WHOIS', fields: f }) }
      case 'http': { let d: any = null; try { d = await httpFetch(`https://${host}`) } catch { try { d = await httpFetch(`http://${host}`) } catch {} }; if (!d) return NextResponse.json({ error: 'Could not reach host' }, { status: 502 }); const h = d.headers; return NextResponse.json({ success: true, type: 'HTTP Inspect', fields: { Domain: host, Status: String(d.status), Server: h['server'] ?? '-', 'Content-Type': h['content-type'] ?? '-' } }) }
      case 'subdomains': { const common = ['www','mail','ftp','api','app','dev','staging','blog','shop','cdn','admin','portal','secure','vpn','remote','support','help','docs','status']; const found: string[] = []; await Promise.allSettled(common.map(s => dns.resolve4(`${s}.${host}`).then(() => found.push(`${s}.${host}`)))); return NextResponse.json({ success: true, type: 'Subdomains', fields: { Domain: host, Found: String(found.length), ...(found.length ? { List: found.join(', ') } : {}) } }) }
      case 'ssl': { const f = await sslCheck(host); return NextResponse.json({ success: true, type: 'SSL / TLS', fields: { Domain: host, ...f } }) }
      case 'websocket': { const paths = ['/', '/ws', '/socket', '/socket.io', '/websocket', '/live', '/api/ws', '/chat']; const rows: { Path: string; Status: string; Upgraded: string }[] = []; let found = false; for (const p of paths) { const r = await checkWS(host, p); if (r.upgraded) found = true; rows.push({ Path: p, Status: r.status, Upgraded: r.upgraded ? 'Yes' : 'No' }) }; return NextResponse.json({ success: true, type: 'WebSocket', fields: { Domain: host, 'WS Found': found ? 'Yes' : 'No', Paths: String(paths.length), Active: String(rows.filter(r => r.Upgraded === 'Yes').length) }, rows }) }
      case 'ping': { const start = Date.now(); let ok = false, ms = 0, code = 0; try { const r = await httpFetch(`https://${host}`, 6000); ms = Date.now() - start; ok = true; code = r.status } catch { try { const r = await httpFetch(`http://${host}`, 6000); ms = Date.now() - start; ok = true; code = r.status } catch {} }; return NextResponse.json({ success: true, type: 'Ping', fields: { Host: host, Reachable: ok ? 'Yes' : 'No', Response: ok ? `${ms}ms` : 'N/A', HTTP: ok ? String(code) : 'N/A' } }) }
      case 'port-scan': { const PORTS: [number, string][] = [[21,'FTP'],[22,'SSH'],[25,'SMTP'],[80,'HTTP'],[110,'POP3'],[143,'IMAP'],[443,'HTTPS'],[465,'SMTPS'],[587,'SMTP/TLS'],[993,'IMAPS'],[995,'POP3S'],[3306,'MySQL'],[5432,'PostgreSQL'],[6379,'Redis'],[8080,'HTTP-Alt'],[8443,'HTTPS-Alt']]; const rows: { Port: string; Service: string; Status: string }[] = []; await Promise.allSettled(PORTS.map(([port, svc]) => new Promise<void>(resolve => { const net = require('net'); const s = new net.Socket(); s.setTimeout(1500); s.on('connect', () => { rows.push({ Port: String(port), Service: svc, Status: 'open' }); s.destroy(); resolve() }); s.on('timeout', () => { rows.push({ Port: String(port), Service: svc, Status: 'closed' }); s.destroy(); resolve() }); s.on('error', () => { rows.push({ Port: String(port), Service: svc, Status: 'closed' }); s.destroy(); resolve() }); s.connect(port, host) }))); rows.sort((a, b) => Number(a.Port) - Number(b.Port)); return NextResponse.json({ success: true, type: 'Port Scanner', fields: { Host: host, Open: String(rows.filter(r => r.Status === 'open').length) }, rows }) }
      case 'http-response-time': { const times: number[] = []; for (let i = 0; i < 3; i++) { const t = Date.now(); try { await httpFetch(`https://${host}`, 6000); times.push(Date.now() - t) } catch {} }; const avg = times.length ? Math.round(times.reduce((a, b) => a + b, 0) / times.length) : null; return NextResponse.json({ success: true, type: 'Response Time', fields: { Host: host, Avg: avg !== null ? `${avg}ms` : 'N/A', Samples: String(times.length) } }) }
      case 'hosting': { let d: any = null; try { d = await httpFetch(`https://${host}`) } catch {}; const h = d?.headers ?? {}; const srv = (h['server'] ?? '').toLowerCase(); let p = 'Unknown', c = 'None'; if (h['cf-ray']) { p = 'Cloudflare'; c = 'Cloudflare' } else if (h['x-vercel-id']) { p = 'Vercel'; c = 'Vercel' } else if (h['x-nf-request-id']) { p = 'Netlify'; c = 'Netlify' } else if (h['x-amz-cf-id'] || srv.includes('amazons3')) { p = 'AWS'; c = 'CloudFront' } else if (srv.includes('cloudfront')) { p = 'AWS'; c = 'CloudFront' } else if (srv.includes('azure')) { p = 'Azure' } else if (srv.includes('gws') || srv.includes('google')) { p = 'Google' } else if (srv) p = srv; return NextResponse.json({ success: true, type: 'Hosting/CDN', fields: { Domain: host, Status: d ? String(d.status) : 'N/A', Provider: p, CDN: c } }) }
      case 'security-headers': { let d: any = null; try { d = await httpFetch(`https://${host}`) } catch {}; const h = d?.headers ?? {}; const checks: [string, string][] = [['CSP','content-security-policy'],['HSTS','strict-transport-security'],['X-Frame-Options','x-frame-options'],['X-Content-Type','x-content-type-options'],['X-XSS-Protection','x-xss-protection'],['Referrer-Policy','referrer-policy'],['Permissions-Policy','permissions-policy'],['COOP','cross-origin-opener-policy'],['CORP','cross-origin-resource-policy'],['COEP','cross-origin-embedder-policy']]; const f: Record<string, string> = { Domain: host }; let score = 0; for (const [label, key] of checks) { f[label] = h[key] ?? 'Missing'; if (h[key]) score += 10 }; f['Score'] = String(score); return NextResponse.json({ success: true, type: 'Security Headers', fields: f }) }
      case 'all-in-one': { const f: Record<string, string> = { Domain: host }; try { const [a, ns, mx] = await Promise.allSettled([dns.resolve4(host), dns.resolveNs(host), dns.resolveMx(host)]); if (a.status === 'fulfilled') f['IP'] = a.value[0] ?? ''; if (ns.status === 'fulfilled') f['NS'] = ns.value.join(', '); if (mx.status === 'fulfilled') f['MX'] = mx.value.map(r => r.exchange).join(', ') } catch {}; try { const d = await httpFetch(`https://${host}`); f['HTTP'] = String(d.status); f['Server'] = d.headers['server'] ?? '-' } catch {}; try { Object.assign(f, await sslCheck(host)) } catch {}; return NextResponse.json({ success: true, type: 'All-In-One', fields: f }) }
      case 'geo': { let ip = host; if (!/^(\d{1,3}\.){3}\d{1,3}$/.test(host)) { try { const r = await dns.resolve4(host); ip = r[0] ?? host } catch {} }; const f: Record<string, string> = { 'Domain/IP': host, Resolved: ip !== host ? ip : 'Same' }; try { const r = await fetch(`http://ip-api.com/json/${ip}?fields=country,countryCode,regionName,city,zip,lat,lon,timezone,isp,org,as`, { signal: AbortSignal.timeout(6000) }); if (r.ok) { const g = await r.json() as any; Object.assign(f, { Country: `${g.country ?? ''} (${g.countryCode ?? ''})`, Region: g.regionName ?? '-', City: g.city ?? '-', Coords: `${g.lat ?? ''},${g.lon ?? ''}`, Timezone: g.timezone ?? '-', ISP: g.isp ?? '-', Org: g.org ?? '-', AS: g.as ?? '-' }) } } catch {}; return NextResponse.json({ success: true, type: 'Geo/IP', fields: f }) }
      case 'email': { const email = (rawHost ?? host).trim().toLowerCase(); const f: Record<string, string> = { Email: email }; const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; f['Format'] = re.test(email) ? 'Valid' : 'Invalid'; if (!re.test(email)) { f['Status'] = 'Invalid format'; return NextResponse.json({ success: true, type: 'Email Check', fields: f }) }; const domain = email.split('@')[1]; try { const mx = await dns.resolveMx(domain); f['MX Found'] = 'Yes'; f['MX Servers'] = mx.map(r => `${r.exchange}(${r.priority})`).join(', ') } catch { f['MX Found'] = 'No' }; const disp = ['mailinator.com','guerrillamail.com','10minutemail.com','tempmail.com','yopmail.com','trashmail.com']; f['Disposable'] = disp.some(d => domain === d) ? 'Yes' : 'No'; f['Status'] = f['MX Found'] === 'Yes' ? 'Valid' : 'No MX records'; return NextResponse.json({ success: true, type: 'Email Check', fields: f }) }
      default: return NextResponse.json({ error: `Unknown tool: ${tool}` }, { status: 400 })
    }
  } catch (err) { return NextResponse.json({ error: (err as Error).message ?? 'Scan failed' }, { status: 500 }) }
}