'use client'
import { useState } from 'react'
import { useScan } from '@/lib/use-scan'
import { PageWrapper, PageHeading, InputCard, PrimaryBtn, ProgressBar, ResultsCard, KvRow, ErrorState, CopyButton, Pill } from '../scan-ui'
export function EmailVerifierView({ onScanSaved }: { onScanSaved?: () => void }) {
  const [email, setEmail] = useState(''); const { loading, progress, progressLabel, result, error, run } = useScan(onScanSaved)
  const handleRun = () => run('email', email)
  const ok = result?.fields?.['Format'] === 'Valid'; const mx = result?.fields?.['MX Found'] === 'Yes'
  const copyText = result ? Object.entries(result.fields).map(([k,v]) => `${k}: ${v}`).join('\n') : ''
  return (<PageWrapper><PageHeading title="Email Verifier" subtitle="Validate format, check MX records, detect disposable emails" /><InputCard><div><label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Email Address</label><input type="email" value={email} onChange={e => setEmail(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') handleRun() }} placeholder="user@example.com" className="w-full rounded-xl border border-input bg-background px-4 py-3 text-sm placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40 transition-all font-mono" spellCheck={false} autoCapitalize="none" autoCorrect="off" /></div></InputCard><PrimaryBtn loading={loading} onClick={handleRun} className="mb-4">Verify Email</PrimaryBtn>{loading && <ProgressBar value={progress} label={progressLabel} />}{error && <ErrorState message={error} />}{result && (<><div className="mb-3 flex gap-2"><Pill variant={ok ? 'success' : 'error'}>{ok ? 'VALID' : 'INVALID'}</Pill><Pill variant={mx ? 'success' : 'warning'}>{mx ? 'MX OK' : 'NO MX'}</Pill></div><ResultsCard title="Verification">{Object.entries(result.fields).map(([k,v]) => <KvRow key={k} label={k} value={v} />)}<CopyButton text={copyText} /></ResultsCard></>)}</PageWrapper>)
}