'use client'
import { useState, useEffect, useCallback } from 'react'
import { getHistory, deleteResult, toggleFavorite, clearHistory } from '@/lib/history'
import { PageWrapper, Pill, EmptyState } from '../scan-ui'
import { Star, Trash2, Search, Globe } from 'lucide-react'
import type { ScanResult } from '@/lib/types'
export function HistoryView() {
  const [history, setHistory] = useState<ScanResult[]>([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all')
  const reload = useCallback(() => { let all = getHistory(); const q = query.toLowerCase(); if (q) all = all.filter(r => r.target.toLowerCase().includes(q) || r.type.toLowerCase().includes(q)); if (filter !== 'all') all = all.filter(r => r.type.toLowerCase() === filter.toLowerCase()); setHistory(all) }, [query, filter])
  useEffect(() => { reload() }, [reload])
  const total = getHistory().length; const types = [...new Set(getHistory().map(r => r.type))]
  const tc: Record<string, string> = { dns: 'bg-blue-50 text-blue-600 border-blue-200', ssl: 'bg-emerald-50 text-emerald-600 border-emerald-200', http: 'bg-indigo-50 text-indigo-600 border-indigo-200', geo: 'bg-violet-50 text-violet-600 border-violet-200', security: 'bg-rose-50 text-rose-600 border-rose-200', whois: 'bg-purple-50 text-purple-600 border-purple-200', websocket: 'bg-amber-50 text-amber-600 border-amber-200', hosting: 'bg-pink-50 text-pink-600 border-pink-200' }
  return (<PageWrapper><div className="flex items-center justify-between mb-5"><div><h2 className="text-2xl font-bold text-foreground">Scan History</h2><p className="text-sm text-muted-foreground">{total} total scans</p></div>{total > 0 && <button onClick={() => { if (confirm('Clear all?')) { clearHistory(); reload() } }} className="text-xs text-red-500 hover:text-red-700 font-medium">Clear All</button>}</div><div className="flex items-center gap-2 mb-4"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search..." className="w-full rounded-xl border border-input bg-background pl-9 pr-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20" /></div><select value={filter} onChange={e => setFilter(e.target.value)} className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"><option value="all">All</option>{types.map(t => <option key={t} value={t.toLowerCase()}>{t}</option>)}</select></div>{history.length === 0 ? <EmptyState title="No history" description="Completed scans appear here." /> : (<div className="space-y-2">{history.map(item => { const d = new Date(item.timestamp); return (<div key={item.id} className="bg-card border border-border rounded-2xl p-4 flex items-center gap-4 group"><span className={`shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase border ${tc[item.type.toLowerCase()] ?? 'bg-slate-100 text-slate-600 border-slate-200'}`}>{item.type}</span><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><Globe size={13} className="text-muted-foreground shrink-0" /><p className="font-mono text-sm truncate">{item.target}</p></div></div><Pill variant={item.success ? 'success' : 'error'}>{item.success ? 'OK' : 'FAIL'}</Pill><span className="hidden sm:block text-xs text-muted-foreground whitespace-nowrap">{d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}, {d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</span><div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={() => { toggleFavorite(item.id); reload() }} className={`p-2 rounded-lg ${item.isFavorite ? 'text-amber-500 bg-amber-50' : 'text-muted-foreground hover:text-amber-500'}`}><Star size={13} fill={item.isFavorite ? 'currentColor' : 'none'} /></button><button onClick={() => { deleteResult(item.id); reload() }} className="p-2 rounded-lg text-muted-foreground hover:text-red-500"><Trash2 size={13} /></button></div></div>)})}</div>)}</PageWrapper>)
}