'use client'
import { type ToolId } from '@/lib/types'
import { Globe, ShieldCheck, Zap, Network, Server, Lock, ScanLine, History, Star, ArrowRight, Crown, Sparkles, Activity, BarChart3, MapPin, Mail, Layers } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useAuth, PLAN_CONFIGS, getScanCount } from '@/lib/auth'
import { getHistory } from '@/lib/history'

interface Props { onNavigate: (id: ToolId) => void }
const TOOLS = [
  { id: 'all-in-one' as ToolId, title: 'All-In-One Scan', desc: 'DNS · WHOIS · SSL · HTTP · Geo', icon: ScanLine, color: 'bg-neutral-800 dark:bg-neutral-700' },
  { id: 'domain-tools' as ToolId, title: 'Domain Tools', desc: 'DNS records, WHOIS, HTTP', icon: Globe, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'ssl' as ToolId, title: 'SSL / TLS', desc: 'Certificate chain & cipher', icon: ShieldCheck, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'websocket' as ToolId, title: 'WebSocket', desc: 'WS/WSS detection', icon: Zap, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'network-tools' as ToolId, title: 'Network Tools', desc: 'Ping, ports, latency', icon: Network, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'hosting' as ToolId, title: 'Hosting / CDN', desc: 'Provider detection', icon: Server, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'security-headers' as ToolId, title: 'Security Headers', desc: 'CSP, HSTS, XSS', icon: Lock, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'geo' as ToolId, title: 'Geo / IP', desc: 'Location & ISP', icon: MapPin, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'email-verifier' as ToolId, title: 'Email Verifier', desc: 'Validate emails', icon: Mail, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'bulk-scan' as ToolId, title: 'Bulk Scan', desc: '100 domains (Pro)', icon: Layers, color: 'bg-neutral-700 dark:bg-neutral-600', premium: true },
  { id: 'history' as ToolId, title: 'History', desc: 'Past results', icon: History, color: 'bg-neutral-700 dark:bg-neutral-600' },
  { id: 'favorites' as ToolId, title: 'Favorites', desc: 'Starred scans', icon: Star, color: 'bg-neutral-700 dark:bg-neutral-600' },
]
export function HomeView({ onNavigate }: Props) {
  const { user } = useAuth(); const plan = user?.plan ?? 'free'; const scansToday = getScanCount(); const totalScans = getHistory().length
  return (<div className="max-w-5xl mx-auto px-4 py-8 pb-20"><div className="text-center mb-8"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent text-accent-foreground text-[11px] font-semibold mb-4"><Sparkles size={12} />PROFESSIONAL DOMAIN INTELLIGENCE</div><h1 className="text-3xl sm:text-4xl font-bold mb-2"><span className="font-bold">Domain Toolkit</span><span className="text-foreground"> Pro</span></h1><p className="text-muted-foreground text-sm max-w-md mx-auto">Real-time DNS, WHOIS, SSL, Geo, HTTP.</p></div><div className="grid grid-cols-3 gap-3 mb-8"><div className="bg-card border border-border rounded-2xl p-4 text-center card-hover"><Activity size={18} className="mx-auto mb-2" /><p className="text-2xl font-bold">{scansToday}</p><p className="text-[10px] text-muted-foreground uppercase tracking-wider">Scans Today</p></div><div className="bg-card border border-border rounded-2xl p-4 text-center card-hover"><BarChart3 size={18} className="mx-auto mb-2" /><p className="text-2xl font-bold">{totalScans}</p><p className="text-[10px] text-muted-foreground uppercase tracking-wider">Total Scans</p></div><div className="bg-card border border-border rounded-2xl p-4 text-center card-hover"><Crown size={18} className={cn('mx-auto mb-2', plan==='free'?'text-muted-foreground':'')} /><p className="text-2xl font-bold">{PLAN_CONFIGS[plan].name}</p><p className="text-[10px] text-muted-foreground uppercase tracking-wider">Plan</p></div></div><button onClick={() => onNavigate('all-in-one')} className="w-full mb-6 p-5 rounded-2xl bg-foreground text-background hover:opacity-90 transition-all group"><div className="flex items-center justify-between"><div className="text-left"><div className="flex items-center gap-2 mb-2"><ScanLine size={20} className="opacity-80" /><span className="text-[10px] font-semibold uppercase tracking-widest opacity-60">Start Here</span></div><p className="font-bold text-lg">All-In-One Domain Scan</p><p className="text-sm opacity-60 mt-0.5">DNS · WHOIS · SSL · HTTP · Geo · Security — one click</p></div><ArrowRight size={22} className="opacity-50 group-hover:translate-x-1 transition-transform" /></div></button><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">{TOOLS.filter(t => t.id !== 'all-in-one').map(tool => { const Icon = tool.icon; return (<button key={tool.id} onClick={() => onNavigate(tool.id)} className="group relative rounded-2xl border border-border bg-card p-4 text-left card-hover"><div className={cn('w-9 h-9 rounded-xl flex items-center justify-center mb-3', tool.color)}><Icon size={18} className="text-white" /></div><p className="font-semibold text-[13px]">{tool.title}</p><p className="text-[11px] text-muted-foreground mt-0.5">{tool.desc}</p>{(tool as any).premium && <span className="absolute top-3 right-3 text-[9px] font-bold px-1.5 py-0.5 rounded-md bg-amber-100 text-amber-600 dark:bg-amber-900/30 dark:text-amber-400 uppercase">PRO</span>}</button>)})}</div></div>)
}