'use client'
import { useState } from 'react'
import { useScan } from '@/lib/use-scan'
import { PageWrapper, PageHeading, InputCard, DomainInput, ToolSelect, PrimaryBtn, ProgressBar, ResultsCard, KvRow, ErrorState, CopyButton } from '../scan-ui'
const TOOLS = [{ value: 'ping', label: 'Ping / Reachability' },{ value: 'port-scan', label: 'Port Scanner (16 ports)' },{ value: 'http-response-time', label: 'HTTP Response Time (3 samples)' }]
export function NetworkToolsView({ onScanSaved }: { onScanSaved?: () => void }) {
  const [host, setHost] = useState(''); const [tool, setTool] = useState('ping'); const { loading, progress, progressLabel, result, error, run } = useScan(onScanSaved)
  const copyText = result ? Object.entries(result.fields).map(([k,v]) => `${k}: ${v}`).join('\n') : ''
  return (<PageWrapper><PageHeading title="Network Tools" subtitle="Ping, port scan, response time" /><InputCard><DomainInput value={host} onChange={setHost} onScanStart={() => run(tool, host)} /><div className="mt-4"><ToolSelect value={tool} onChange={setTool} options={TOOLS} label="Tool" /></div></InputCard><PrimaryBtn loading={loading} onClick={() => run(tool, host)} className="mb-4">Run Test</PrimaryBtn>{loading && <ProgressBar value={progress} label={progressLabel} />}{error && <ErrorState message={error} />}{result && (<ResultsCard title={result.type || 'Results'}>{Object.entries(result.fields).map(([k,v]) => <KvRow key={k} label={k} value={v} />)}{result.rows && <div className="px-5 py-3"><div className="space-y-1">{result.rows.map((r,i) => (<div key={i} className="flex items-center gap-3 text-xs font-mono"><span className="w-16">{r['Port']}</span><span className="w-20 text-muted-foreground">{r['Service']}</span><span className={r['Status']==='open'?'text-emerald-500 font-bold':'text-muted-foreground'}>{r['Status']}</span></div>))}</div></div>}<CopyButton text={copyText} /></ResultsCard>)}</PageWrapper>)
}