'use client'
import { useState } from 'react'
import { checkAllWebSocketPaths } from '@/lib/websocket-checker'
import { PageWrapper, PageHeading, InputCard, DomainInput, PrimaryBtn, ProgressBar, ResultsCard, KvRow, ErrorState, CopyButton, Pill, InfoBar } from '../scan-ui'
import type { ScanResult } from '@/lib/types'
const PATHS = ['/', '/ws', '/socket', '/socket.io', '/websocket', '/live', '/api/ws', '/chat']
export function WebSocketView({ onScanSaved }: { onScanSaved?: () => void }) {
  const [host, setHost] = useState(''); const [loading, setLoading] = useState(false); const [progress, setProgress] = useState(0)
  const [progressLabel, setProgressLabel] = useState(''); const [result, setResult] = useState<ScanResult | null>(null); const [error, setError] = useState('')
  const handleRun = async () => { const t = host.replace(/^https?:\/\//i,'').replace(/^wss?:\/\//i,'').split('/')[0].trim().toLowerCase(); if(!t){setError('Enter a domain.');return}; setLoading(true); setProgress(10); setProgressLabel('Scanning...'); setError(''); setResult(null); const iv = setInterval(() => setProgress(p => p < 85 ? p + 8 : p), 400); try { const r = await checkAllWebSocketPaths(t, PATHS); clearInterval(iv); setProgress(100); setProgressLabel('Done'); setResult({ id: `${Date.now()}`, type: 'websocket', target: t, timestamp: Date.now(), success: true, fields: r.fields, rows: r.rows }); onScanSaved?.() } catch (err) { setError((err as Error).message) } finally { setLoading(false) } }
  const found = result?.fields?.['WebSocket Found'] === 'Yes'
  const copyText = result ? Object.entries(result.fields).map(([k,v]) => `${k}: ${v}`).join('\n') : ''
  return (<PageWrapper><PageHeading title="WebSocket Tester" subtitle="RFC 6455 WS/WSS detection via browser WebSocket API" /><InfoBar items={PATHS} /><InputCard><DomainInput value={host} onChange={setHost} onScanStart={handleRun} /></InputCard><PrimaryBtn loading={loading} onClick={handleRun} className="mb-4">Check WebSocket</PrimaryBtn>{loading && <ProgressBar value={progress} label={progressLabel} />}{error && <ErrorState message={error} />}{result && (<><div className="mb-3"><Pill variant={found ? 'success' : 'warning'}>{found ? 'WS FOUND' : 'NOT FOUND'}</Pill></div><ResultsCard title="Results">{Object.entries(result.fields).map(([k,v]) => <KvRow key={k} label={k} value={v} />)}{result.rows && <div className="px-5 py-3"><div className="space-y-1">{result.rows.map((r,i) => (<div key={i} className="flex items-center gap-3"><span className="text-xs font-mono">{r['Path']}</span><span className="text-xs text-muted-foreground">{r['Status']}</span><Pill variant={r['Upgraded']==='Yes'?'success':'muted'}>{r['Upgraded']==='Yes'?'OK':'-'}</Pill></div>))}</div></div>}<CopyButton text={copyText} /></ResultsCard></>)}</PageWrapper>)
}