'use client'
import { Lock, Crown } from 'lucide-react'
import { useAuth, isPlanAllowed, canBulkScan } from '@/lib/auth'
interface Props { toolId: string; children: React.ReactNode }
export function PaywallGate({ toolId, children }: Props) {
  const { user, openPricing, openAuthModal } = useAuth(); const plan = user?.plan ?? 'free'
  if (toolId === 'bulk-scan' ? canBulkScan(plan) : isPlanAllowed(plan, toolId)) return <>{children}</>
  const anon = !user; const name = 'Pro'
  return (<div className="relative overflow-hidden"><div className="pointer-events-none select-none blur-[3px] opacity-30 saturate-50">{children}</div><div className="absolute inset-0 flex items-start justify-center pt-20 px-4"><div className="w-full max-w-sm bg-card border border-border rounded-2xl p-7 text-center shadow-2xl"><div className="w-14 h-14 rounded-2xl bg-accent flex items-center justify-center mx-auto mb-4"><Lock size={22} className="text-primary" /></div><div className="flex items-center justify-center gap-1.5 mb-2"><Crown size={14} className="text-primary" /><span className="text-xs font-bold text-primary uppercase tracking-wide">{name} Required</span></div><h3 className="font-bold text-lg text-foreground mb-2">Unlock This Tool</h3><p className="text-sm text-muted-foreground mb-5">{anon ? 'Sign up and upgrade to Pro.' : 'Upgrade to Pro for full access.'}</p><div className="flex flex-wrap gap-1.5 justify-center mb-5">{['100 domains','Export','All modes','Favorites'].map(b => (<span key={b} className="px-2 py-1 rounded-full bg-accent text-accent-foreground text-[11px] font-semibold">{b}</span>))}</div>{anon ? (<div className="flex flex-col gap-2.5"><button onClick={() => openAuthModal('signup')} className="w-full rounded-xl gradient-btn py-3 text-sm font-semibold">Create free account</button><button onClick={() => openAuthModal('signin')} className="w-full rounded-xl border border-border py-2.5 text-sm font-medium hover:bg-secondary">Sign in</button></div>) : (<button onClick={openPricing} className="w-full rounded-xl gradient-btn py-3 text-sm font-semibold flex items-center justify-center gap-2"><Crown size={15} />Upgrade to {name}</button>)}</div></div></div>)
}