'use client'
import { Lock, Crown } from 'lucide-react'
import { useAuth, isPlanAllowed, type Plan } from '@/lib/auth'

interface PaywallGateProps { toolId: string; requiredPlan?: Plan; children: React.ReactNode }
export function PaywallGate({ toolId, requiredPlan = 'pro', children }: PaywallGateProps) {
  const { user, openPricing, openAuthModal } = useAuth()
  const allowed = isPlanAllowed(user?.plan ?? 'free', toolId)
  if (allowed) return <>{children}</>
  const isNotLoggedIn = !user
  const planName = requiredPlan === 'business' ? 'Business' : 'Pro'
  return (<div className="relative overflow-hidden"><div className="pointer-events-none select-none blur-[3px] opacity-30 saturate-50" aria-hidden="true">{children}</div><div className="absolute inset-0 flex items-start justify-center pt-16 px-4"><div className="w-full max-w-sm glass rounded-2xl p-7 text-center shadow-2xl"><div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-4"><Lock size={22} className="text-primary" /></div><div className="flex items-center justify-center gap-1.5 mb-2"><Crown size={14} className="text-primary" /><span className="text-xs font-bold text-primary uppercase tracking-wide">{planName} required</span></div><h3 className="font-bold text-lg text-foreground mb-2">Unlock this tool</h3><p className="text-sm text-muted-foreground mb-5 leading-relaxed">{isNotLoggedIn ? 'Sign up and upgrade to access this feature.' : `Upgrade to ${planName} for full access.`}</p><div className="flex flex-wrap gap-1.5 justify-center mb-5">{['All tools', '100+ scans/day', 'Export results', 'Favorites'].map(b => (<span key={b} className="px-2 py-1 rounded-full bg-primary/8 text-primary text-[11px] font-semibold border border-primary/15">{b}</span>))}</div>{isNotLoggedIn ? (<div className="flex flex-col gap-2.5"><button onClick={() => openAuthModal('signup')} className="w-full rounded-xl bg-gradient-to-r from-cyan to-accent text-white py-3 text-sm font-semibold hover:shadow-[0_0_25px_rgba(124,58,237,0.2)] transition-all">Create free account</button><button onClick={() => openAuthModal('signin')} className="w-full rounded-xl border border-border py-2.5 text-sm font-medium text-foreground hover:bg-secondary transition-colors">Sign in</button></div>) : (<button onClick={openPricing} className="w-full rounded-xl bg-gradient-to-r from-cyan to-accent text-white py-3 text-sm font-semibold hover:shadow-[0_0_25px_rgba(124,58,237,0.2)] transition-all flex items-center justify-center gap-2"><Crown size={15} />Upgrade to {planName}</button>)}</div></div></div>)
}