'use client'
import { cn } from '@/lib/utils'
import { Copy, Check, Search } from 'lucide-react'
import { useState, useCallback, useRef, useEffect } from 'react'
import { suggestDomains, addDomainToHistory } from '@/lib/scan-history'

export function PageWrapper({ children }: { children: React.ReactNode }) { return <div className="max-w-3xl mx-auto px-4 py-6 pb-24">{children}</div> }
export function PageHeading({ title, subtitle }: { title: string; subtitle?: string }) { return (<div className="mb-6"><h2 className="text-2xl font-bold text-foreground">{title}</h2>{subtitle && <p className="text-sm text-muted-foreground mt-1.5">{subtitle}</p>}</div>) }
export function InputCard({ children }: { children: React.ReactNode }) { return <div className="bg-card border border-border rounded-2xl p-5 mb-4 shadow-sm">{children}</div> }

interface DomainInputProps { value: string; onChange: (v: string) => void; placeholder?: string; label?: string; onScanStart?: (domain: string) => void }
export function DomainInput({ value, onChange, placeholder = 'example.com', label = 'Domain', onScanStart }: DomainInputProps) {
  const [showSuggestions, setShowSuggestions] = useState(false); const [suggestions, setSuggestions] = useState<string[]>([])
  const inputRef = useRef<HTMLInputElement>(null); const dropdownRef = useRef<HTMLDivElement>(null)
  useEffect(() => { const s = suggestDomains(value); setSuggestions(s); setShowSuggestions(s.length > 0 && document.activeElement === inputRef.current) }, [value])
  useEffect(() => { const h = (e: MouseEvent) => { if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node) && inputRef.current && !inputRef.current.contains(e.target as Node)) setShowSuggestions(false) }; document.addEventListener('mousedown', h); return () => document.removeEventListener('mousedown', h) }, [])
  const selectSuggestion = (domain: string) => { onChange(domain); setShowSuggestions(false); inputRef.current?.focus() }
  return (<div className="relative"><label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">{label}</label><div className="relative"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none" /><input ref={inputRef} type="text" value={value} onChange={e => { onChange(e.target.value); setShowSuggestions(true) }} onFocus={() => { const s = suggestDomains(value); setSuggestions(s); if (s.length > 0) setShowSuggestions(true) }} onKeyDown={e => { if (e.key === 'Enter' && onScanStart) { setShowSuggestions(false); addDomainToHistory(value); onScanStart(value) } }} placeholder={placeholder} className="w-full rounded-xl border border-input bg-background pl-10 pr-4 py-3 text-sm placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40 transition-all font-mono" spellCheck={false} autoCapitalize="none" autoCorrect="off" />{value && <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[11px] text-muted-foreground font-mono">↵ Enter</span>}</div>{showSuggestions && suggestions.length > 0 && (<div ref={dropdownRef} className="absolute z-20 left-0 right-0 top-full mt-2 bg-card border border-border rounded-xl shadow-xl overflow-hidden">{suggestions.map((d, i) => (<button key={i} type="button" onClick={() => selectSuggestion(d)} className="w-full text-left px-4 py-2.5 text-sm text-foreground hover:bg-accent transition-colors border-b border-border last:border-0 flex items-center gap-2"><span className="text-xs">🌐</span><span className="font-mono">{d}</span></button>))}</div>)}</div>)
}

export function BulkDomainInput({ value, onChange, label = 'Domains (one per line)' }: { value: string; onChange: (v: string) => void; label?: string }) { return (<div><label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">{label}</label><textarea value={value} onChange={e => onChange(e.target.value)} placeholder={'example.com\ngoogle.com\ngithub.com'} rows={6} className="w-full rounded-xl border border-input bg-background px-4 py-3 text-sm placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40 transition-all font-mono resize-none" spellCheck={false} autoCapitalize="none" autoCorrect="off" /></div>) }

export function ToolSelect({ value, onChange, options, label = 'Tool' }: { value: string; onChange: (v: string) => void; options: { value: string; label: string }[]; label?: string }) { return (<div><label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">{label}</label><select value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-xl border border-input bg-background px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40 transition-all">{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div>) }

export function PrimaryBtn({ loading, children, className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean }) { return (<button {...props} disabled={loading || props.disabled} className={cn('w-full rounded-xl font-semibold text-sm py-3.5 gradient-btn disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:shadow-none', className)}>{loading ? (<span className="flex items-center justify-center gap-2"><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />Running...</span>) : children}</button>) }

export function ProgressBar({ value, label }: { value: number; label?: string }) { return (<div className="mb-4"><div className="h-2 bg-secondary rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-primary to-violet-500 rounded-full transition-all duration-500" style={{ width: `${value}%` }} /></div>{label && <p className="text-xs text-muted-foreground mt-1.5 font-mono">{label}</p>}</div>) }

export function ResultsCard({ title, children }: { title?: string; children: React.ReactNode }) { return (<div className="bg-card border border-border rounded-2xl shadow-sm mb-4 overflow-hidden">{title && (<div className="flex items-center gap-3 px-5 py-4 border-b border-border"><span className="w-1.5 h-5 rounded-full bg-gradient-to-b from-primary to-violet-500 shrink-0" /><h3 className="font-semibold text-sm text-foreground">{title}</h3></div>)}<div className="divide-y divide-border">{children}</div></div>) }

export function KvRow({ label, value }: { label: string; value: string }) { return (<div className="flex items-start gap-4 px-5 py-3"><span className="text-[12px] font-semibold text-muted-foreground min-w-[130px] shrink-0 pt-0.5 uppercase tracking-wider">{label}</span><span className="text-sm text-foreground font-mono break-all flex-1">{value || '—'}</span></div>) }

type PillVariant = 'success' | 'error' | 'warning' | 'primary' | 'muted'
export function Pill({ children, variant = 'primary' }: { children: React.ReactNode; variant?: PillVariant }) { const s: Record<PillVariant, string> = { success: 'bg-emerald-50 text-emerald-600 border-emerald-200', error: 'bg-red-50 text-red-600 border-red-200', warning: 'bg-amber-50 text-amber-600 border-amber-200', primary: 'bg-indigo-50 text-indigo-600 border-indigo-200', muted: 'bg-slate-100 text-slate-500 border-slate-200' }; return <span className={cn('inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wider border', s[variant])}>{children}</span> }

export function CopyButton({ text }: { text: string }) { const [copied, setCopied] = useState(false); const copy = useCallback(() => { navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000) }) }, [text]); return (<button onClick={copy} className="flex items-center gap-2 text-xs text-muted-foreground hover:text-primary transition-colors px-5 py-3 font-medium">{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? 'Copied!' : 'Copy results'}</button>) }

export function ErrorState({ message }: { message: string }) { return (<div className="bg-red-50 border border-red-200 rounded-2xl p-4 mb-4"><p className="text-sm text-red-600 font-medium">{message}</p></div>) }

export function EmptyState({ title, description }: { title: string; description: string }) { return (<div className="flex flex-col items-center justify-center py-16 text-center px-4"><div className="w-16 h-16 rounded-2xl bg-secondary flex items-center justify-center mb-4"><span className="text-muted-foreground text-2xl">🔍</span></div><p className="font-semibold text-foreground mb-1.5">{title}</p><p className="text-sm text-muted-foreground max-w-xs">{description}</p></div>) }

export function InfoBar({ items }: { items: string[] }) { return (<div className="bg-accent/50 rounded-xl px-4 py-3 mb-4 border border-accent"><p className="text-xs font-semibold text-accent-foreground uppercase tracking-wide mb-1.5">Scanned paths</p><p className="text-xs font-mono text-foreground">{items.join('  ·  ')}</p></div>) }