'use client'

import { NAV_ITEMS, type ToolId } from '@/lib/types'
import { Home, ScanLine, Globe, ShieldCheck, Zap, Network, Server, Lock, History, Star, X, Crown, Settings } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useAuth, PLAN_CONFIGS, type Plan } from '@/lib/auth'

const ICON_MAP: Record<string, React.ElementType> = { home: Home, scan: ScanLine, globe: Globe, shield: ShieldCheck, zap: Zap, network: Network, server: Server, lock: Lock, history: History, star: Star, crown: Crown, settings: Settings }
const PLAN_BADGE_COLORS: Record<Plan, string> = { free: 'bg-muted text-muted-foreground', pro: 'bg-primary/15 text-primary', business: 'bg-amber-500/15 text-amber-600' }

interface SidebarProps { activeId: ToolId; onNavigate: (id: ToolId) => void; isOpen: boolean; onClose: () => void }

export function Sidebar({ activeId, onNavigate, isOpen, onClose }: SidebarProps) {
  return (<><aside className="hidden lg:flex flex-col w-64 shrink-0 bg-sidebar border-r border-sidebar-border h-screen"><SidebarContent activeId={activeId} onNavigate={onNavigate} /></aside><aside className={cn('fixed inset-y-0 left-0 z-40 flex flex-col w-72 bg-sidebar border-r border-sidebar-border transition-transform duration-260 ease-out lg:hidden', isOpen ? 'translate-x-0' : '-translate-x-full')} aria-label="Navigation drawer"><div className="flex items-center justify-between px-4 py-3 border-b border-sidebar-border"><span className="font-bold text-sidebar-foreground text-sm">Domain Toolkit Pro</span><button onClick={onClose} className="p-1.5 rounded-md hover:bg-sidebar-accent text-sidebar-foreground" aria-label="Close menu"><X size={18} /></button></div><SidebarContent activeId={activeId} onNavigate={onNavigate} /></aside></>)
}

function SidebarContent({ activeId, onNavigate }: { activeId: ToolId; onNavigate: (id: ToolId) => void }) {
  const { user } = useAuth()
  const mainItems = NAV_ITEMS.filter(i => !i.hidden && i.id !== 'pricing')
  return (<div className="flex flex-col h-full overflow-hidden"><div className="px-5 py-5 border-b border-sidebar-border hidden lg:block"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shrink-0"><Globe size={16} className="text-primary-foreground" /></div><div><p className="font-bold text-sidebar-foreground text-sm leading-tight">Domain Toolkit</p><p className="text-xs text-muted-foreground leading-tight">Pro</p></div></div></div><nav className="flex-1 overflow-y-auto py-2 px-2" aria-label="Main navigation">{mainItems.map(item => { const Icon = ICON_MAP[item.icon] ?? Globe; const isActive = item.id === activeId; return (<button key={item.id} onClick={() => onNavigate(item.id)} className={cn('w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left text-sm transition-colors mb-0.5', isActive ? 'bg-sidebar-accent text-sidebar-primary font-semibold' : 'text-sidebar-foreground hover:bg-sidebar-accent/60 hover:text-sidebar-primary font-normal')} aria-current={isActive ? 'page' : undefined}><Icon size={17} className={cn(isActive ? 'text-sidebar-primary' : 'text-muted-foreground')} aria-hidden="true" /><span className="truncate">{item.label}</span>{isActive && <span className="ml-auto w-1.5 h-1.5 rounded-full bg-sidebar-primary shrink-0" />}</button>)})}</nav><div className="px-3 py-3 border-t border-sidebar-border flex flex-col gap-1.5">{user && user.plan !== 'business' ? (<button onClick={() => onNavigate('pricing')} className={cn('w-full flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-left text-sm font-semibold transition-colors', activeId === 'pricing' ? 'bg-primary text-primary-foreground' : 'bg-primary/10 text-primary hover:bg-primary/15')}><Crown size={15} /><span>{user.plan === 'free' ? 'Upgrade to Pro' : 'Go Business'}</span></button>) : !user ? (<button onClick={() => onNavigate('pricing')} className={cn('w-full flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-left text-sm font-semibold transition-colors', activeId === 'pricing' ? 'bg-primary text-primary-foreground' : 'bg-primary/10 text-primary hover:bg-primary/15')}><Crown size={15} /><span>View Plans</span></button>) : (<div className="flex items-center gap-2 px-3 py-2"><span className={cn('px-2 py-0.5 rounded-full text-[11px] font-bold', PLAN_BADGE_COLORS[user.plan])}>{PLAN_CONFIGS[user.plan].name}</span><span className="text-xs text-muted-foreground truncate">{user.name}</span></div>)}<button onClick={() => onNavigate('admin')} className="w-full flex items-center gap-2.5 px-3 py-1.5 rounded-lg text-left text-[11px] text-muted-foreground/40 hover:text-muted-foreground transition-colors" aria-label="Admin"><Settings size={12} />Admin</button></div></div>)
}