'use client'
import { useState, useRef, useEffect } from 'react'
import { LogOut, Crown, ChevronDown, User } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useAuth, signOut, PLAN_CONFIGS } from '@/lib/auth'

export function UserMenu() {
  const { user, setUser, openAuthModal, openPricing } = useAuth()
  const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null)
  useEffect(() => { const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false) }; document.addEventListener('mousedown', h); return () => document.removeEventListener('mousedown', h) }, [])
  if (!user) return (<div className="flex items-center gap-2"><button onClick={() => openAuthModal('signin')} className="px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground rounded-lg hover:bg-secondary">Sign in</button><button onClick={() => openAuthModal('signup')} className="px-3 py-1.5 text-xs font-semibold btn-primary rounded-lg">Sign up</button></div>)
  const initials = user.name.split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase()
  return (<div className="relative" ref={ref}><button onClick={() => setOpen(o => !o)} className="flex items-center gap-2 px-2 py-1.5 rounded-xl hover:bg-secondary transition-colors"><div className="w-7 h-7 rounded-full btn-primary flex items-center justify-center shrink-0"><span className="text-[10px] font-bold">{initials}</span></div><ChevronDown size={14} className="text-muted-foreground shrink-0" /></button>{open && (<div className="absolute right-0 top-full mt-2 w-56 bg-card border border-border rounded-xl shadow-xl z-50 overflow-hidden"><div className="px-4 py-3 border-b border-border"><p className="text-sm font-semibold text-foreground truncate">{user.name}</p><p className="text-xs text-muted-foreground truncate">{user.email}</p><span className={cn('inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold mt-1.5', user.plan === 'business' ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' : user.plan === 'pro' ? 'bg-accent text-accent-foreground' : 'bg-secondary text-muted-foreground')}>{user.plan !== 'free' && <Crown size={10} />}{PLAN_CONFIGS[user.plan].name}</span></div>{user.plan !== 'business' && <button onClick={() => { openPricing(); setOpen(false) }} className="w-full flex items-center gap-2.5 px-4 py-2.5 text-sm font-semibold hover:bg-accent transition-colors text-left"><Crown size={15} /> {user.plan === 'free' ? 'Upgrade to Pro' : 'Go Business'}</button>}<button onClick={() => { signOut(); setUser(null); setOpen(false) }} className="w-full flex items-center gap-2.5 px-4 py-2.5 text-sm text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors text-left"><LogOut size={15} /> Sign out</button></div>)}</div>)
}